### PR TITLE
Expose streaming API

### PR DESCRIPTION
**Pull request by reuben**
Uplift of some work we did in DeepSpeech to expose a streaming API for the decoder. This basically refactors the implementation to work in three stages: initialization, processing of probability vectors, and decoding. The old batch API is then rewritten in terms of the streaming API.

The diff looks noisier than it actually is, most of the changes is just replacing local variables with DecoderState members. It could probably be simplified by making the streaming implementation work as methods in the DecoderState rather than standalone functions.

`ctc_beam_search_decoder_stream_decode` has some ugly workaround for allowing intermediate decode calls while streaming is still happening, we can't sort the prefixes in-place otherwise it affects scoring from that point onward, so some ugly copying is made and the sorting is done via external scores.

### CODE REVIEW

**Comment by reuben** [comment]
Sorry, I had some uncommitted changes. I updated the PR.

**Comment by SeanNaren** [comment]
This is awesome! Could we get some form of test/example on how to use this?

**Comment by reuben** [comment]
Sorry for the delay answering this, I somehow missed the email.

> Could we get some form of test/example on how to use this?

Well, there's `ctc_beam_search_decoder`, which is implemented in terms of the streaming API. Any current tests will exercise this code through that. Not sure how to write a better example as this is geared more towards advanced users, you'd already need to have a streaming acoustic model to then integrate this streaming decoder with.

**Comment by reuben** [comment]
I've since simplified this change by making init/next/decode be methods of the DecoderState, I'll uplift the changes into this PR shortly.

**Comment by SeanNaren** [comment]
Sounds good! Once it's ready will merge

**Comment by reuben** [comment]
Updated with the object-oriented approach. As you can see the diff is *much* cleaner, the only differences are related to the out-of-order sorting of the prefixes in `decode` and the handling of absolute vs relative time steps in `next`. This is how it is used: https://github.com/reuben/ctcdecode/blob/ca630b4f27c280716645ad6401e689c07797e393/ctcdecode/src/ctc_beam_search_decoder.cpp#L212-L226

**Comment by reuben** [comment]
I just noticed I also sneaked in a fix for an unrelated issue: https://github.com/parlance/ctcdecode/blob/ca630b4f27c280716645ad6401e689c07797e393/ctcdecode/src/ctc_beam_search_decoder.cpp#L158

Previously the code was deleting the elements of the vector but forgetting to resize it accordingly. Let me know if you prefer that to be in a separate PR.

**Comment by SeanNaren** [comment]
I'll review this and merge, apologies for how long a wait it's been!

**Comment by SeanNaren** [comment]
LGTM, thanks man!

**Pull request merged**
