### PR TITLE
Online Decoding

### PR DESCRIPTION
**Pull request by stas6626**
I wrote simple python bindings for online decoding

### CODE REVIEW

**Comment by stas6626** [comment]
Hello @SeanNaren , can you please review and approve pr, Thanks!

**Comment by SeanNaren** [comment]
hey @stas6626 thanks for making this! I should have time in the rest of the week to have a look, apologies on the delay :)

**Comment by stas6626** [comment]
@SeanNaren No problem! 
I get bug report from @stevenhillis about seq_len growing, thank you for this!
Also, what to say thanks to @nikolsky for help with tricky shape bug!

**Comment by SeanNaren** [comment]
Thanks so much @stas6626, @nikolsky for your work on this, this is a fantastic feature!

**Pull request merged**
